<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="chassis">

    <xacro:macro name="chassis_visual">
        <visual>
            <origin xyz="${0.03-body_reference_x} 0 ${chassis_height-aabb_height/2}"
                rpy="0 0 ${M_PI/2.0}" />
            <geometry>
                <mesh filename="package://aroco_description/meshes/chassis.dae" />
            </geometry>
            <material name="grey">
                <color rgba="0.6 0.6 0.6 1" />
            </material>
        </visual>
    </xacro:macro>


</robot>